questions = [
    {"normal": "What is your favorite city?", "impostor": "Lie about your favorite city."},
    {"normal": "What is your least favorite city?", "impostor": "Lie about your least favorite city."},
    {"normal": "What is your favorite food?", "impostor": "Lie about your favorite food."},
    {"normal": "What is a food you dislike?", "impostor": "Lie about a food you dislike."},
    {"normal": "What is your favorite hobby?", "impostor": "Lie about your favorite hobby."},
    {"normal": "What is a hobby you have never tried?", "impostor": "Lie about a hobby you have never tried."},
    {"normal": "What is your favorite color?", "impostor": "Lie about your favorite color."},
    {"normal": "What is a color you dislike?", "impostor": "Lie about a color you dislike."},
    {"normal": "Where did you grow up?", "impostor": "Lie about where you grew up."},
    {"normal": "What is your dream job?", "impostor": "Lie about your dream job."},
    {"normal": "What is your favorite animal?", "impostor": "Lie about your favorite animal."},
    {"normal": "What is an animal you dislike?", "impostor": "Lie about an animal you dislike."},
    {"normal": "What is your favorite movie genre?", "impostor": "Lie about your favorite movie genre."},
    {"normal": "What is a movie genre you dislike?", "impostor": "Lie about a movie genre you dislike."},
    {"normal": "What is your favorite season?", "impostor": "Lie about your favorite season."},
    {"normal": "What is your least favorite season?", "impostor": "Lie about your least favorite season."},
    {"normal": "What is your favorite sport?", "impostor": "Lie about your favorite sport."},
    {"normal": "What is a sport you dislike?", "impostor": "Lie about a sport you dislike."},
    {"normal": "What is your favorite type of music?", "impostor": "Lie about your favorite type of music."},
    {"normal": "What is a type of music you dislike?", "impostor": "Lie about a type of music you dislike."},
]
